"""Add google_id to users, make password nullable

Revision ID: 3233003bd0db
Revises: 4e900f778fc0
Create Date: 2025-12-31 21:40:46.108081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3233003bd0db'
down_revision = '4e900f778fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
